name: AndSmile
favicon: null
layout_spectrum: 0.9005998878274113
typography_spectrum: 0.4660856709815562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9256749560590833
  lightness: 0.9789614782202989
  saturation: 0.7600001904647797
  rhythmicContrast: 0.6525790698360652
purpose: []
